### ISSUE TITLE
Cannot change anything (all fields are read-only)

### ISSUE THREAD

**Issue by FFrozTT** [Netflix-Skunkworks/Scumblr#248]
I cannot modify anything including:
Results	- Any result parameter (Status, Tag, Assignee)
		- Delete (cannot delete result.)
Tasks	- Any task parameter (Query, Frequency, Tags etc.)

I have another issue where sketchy captures are not showing in the results attachments but I believe its the same issue because that field is read-only and cannot be updated. The sketches are working fine and the callback is setup correctly.

I'm using a new install with generic parameters like no SSL and everything on the same machine etc...

Any time I try to make a change which fails, an error occurs in the development log file:
Can't verify CSRF token authenticity

I've tried searching for this but can't find anything other than an article pointing to device.rb but I've made no modifications to that file.

Any thoughts what to look at?

**Comment by FFrozTT** [comment]
Actually I was able to solve the problem myself.
app/controllers/application_controller.rb:
change
```
class ApplicationController < ActionController::Base
  protect_from_forgery
```
to
```
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
```

change
```
  before_filter :authenticate_user!
  before_filter :require_enabled
```
to
```
  skip_before_action :verify_authenticity_token
  before_filter :authenticate_user!
  before_filter :require_enabled
```

I don't think this has solved my sketchy issue though as Attachments are still not showing up. I can start a new issue for that.

**Comment by sbehrens** [comment]
You may have noticed this message when filing the ticket:

```
This project is no longer supported.  We are actively looking for a maintainer, if you are interested please reach out to sbehrens@netflix.com
```

I wanted to let you know we're working on transitioning the project to a new maintainer.  Feel free to file an issue and when he takes over I'm sure he can take a look.

**Comment by FFrozTT** [comment]
Ya I saw that but I was rolling the dice.  Thanks for all your efforts Scott, I've used Scumblr for years and I love it.
